services:
  app:
    build:
      context: .
      dockerfile: .build/dockerfiles/Dockerfile
      target: dev
    volumes:
      - "./app:/app:cached"
      - "./.data/bob-s-home:/home/bob:cached"
#    ports:
#      - "8080:8080"
#    labels:
#      - com.dnsdock.alias=tpj.docker
    environment:
      - TERM=xterm-256color
      - TZ=Europe/Rome
      - MAVEN_ARGS="--no-transfer-progress"
      - DEBUG_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - APP_NAME=template-project-java
      - APP_PORT=8080
      - APP_ENVIRONMENT=local
      - APP_LOG_LEVEL=DEBUG
      - JAVA_LOG_LEVEL=INFO
